name:                hs-ipfs-api
version:             0.1.0.0
github:              "abueide/hs-ipfs-api"
license:             BSD3
author:              "Andrew Bueide"
maintainer:          "abueide@protonmail.com"
copyright:           "2018 Andrew Bueide"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-ipfs-api#readme>

dependencies:
- base
- servant
- servant-client
- text
- http-client
- time
- MissingH
- aeson
- bytestring
- base64-bytestring
- hspec

library:
  source-dirs: src

executables:
  hs-ipfs-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-ipfs-api

tests:
  hs-ipfs-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-ipfs-api
